### ISSUE TITLE
No longer possible to hide Dashboard (Craft 2.5)

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/CPNav#17] opened 2016-01-09 01:14 UTC
In Craft 2.4, it was possible to hide the Dashboard.

In Craft 2.5, even if you hide the Dashboard, **you'll still be taken there upon login.**

**Comment by badlydrawnrob** [comment] 2016-01-27 19:50
@lindseydiloreto A temporary workaround is to use `'postCpLoginRedirect' => 'myaccount#profile'` [general setting](https://craftcms.com/docs/config-settings#postLoginRedirect). Not ideal, would be nice to hide this from certain groups altogther (I don't know why this isn't built into Craft?!).

**Comment by engram-design** [comment] 2016-02-21 02:21
I'm not _quite_ sure how I want to handle this. On the one hand, I can certainly disable access to section that are hidden, but I'd honestly rather not. 

For example, say you want to hide the Settings page - a handy one to hide so even if your client has an Admin account (for whatever reason), but its still accessible because you know you can enter `/admin/settings` to access it.

I actually have the same setup for all client sites using @badlydrawnrob's suggestion of using `postCpLoginRedirect` to Entries - but thats another story.

What do you think about this one? Should this be a special case for the Dashboard?

**Comment by lindseydiloreto** [comment] 2016-02-21 07:42
@badlydrawnrob: I actually didn't even know about `postCpLoginRedirect`, thanks! I'll give that a shot and see if it helps.

@engram-design: If Rob's solution does the trick, then perhaps it's not necessary to lock the Dashboard down any further. I find that page useless on 90% of my sites, so it's nice when I can make it disappear. :)

**Comment by engram-design** [comment] 2016-02-21 07:47
@lindseydiloreto There you go! FYI, for our clients, we always set the `postCpLoginRedirect` to `entries` - mostly because we figure clients want to get in there and edit their content, rather than look at pretty Analytics widgets (although, they certainly can, and its useful info).

I'm going to close this one, purely on the basis that its expected behaviour to be able to be able to still access hidden pages, and there is a config setting to alter your case.

Let me know if you need it reopened, or if you need to have another crack at this!

**Closed by engram-design** 2016-02-21 07:47 UTC

**Comment by lindseydiloreto** [comment] 2016-02-21 07:49
Sounds perfect, thanks @engram-design!
