### ISSUE TITLE
Plugin hardcodes icon svg paths for plugins

### ISSUE THREAD

**Issue by juresrpcic** [engram-design/CPNav#47] opened 2018-05-09 07:36 UTC
Issue submitted in Craft 3's tracker initially - all details there: https://github.com/craftcms/cms/issues/2643

**Comment by engram-design** [comment] 2018-05-09 13:13
@juresrpcic Are you on the latest of Craft + CP Nav? EDIT: Ah, I can see the issue.

**Comment by engram-design** [comment] 2018-05-09 13:58
Fixed in [2.0.6](https://github.com/verbb/cp-nav/releases/tag/2.0.6).

**Closed as completed by engram-design** 2018-05-09 13:58 UTC

**Comment by gfra54** [comment] 2020-03-03 09:40
Hello, @engram-design I have the same problem, while being on cp-nav 3.0.4 on a Craft CMS 3.4.9 installation on a local windows machine 
![image](https://user-images.githubusercontent.com/1954396/75762551-25fcce80-5d3b-11ea-9e8a-200245e31443.png)
![image](https://user-images.githubusercontent.com/1954396/75762622-43ca3380-5d3b-11ea-8920-058fb1fa7e7c.png)
![image](https://user-images.githubusercontent.com/1954396/75762665-5e041180-5d3b-11ea-8888-7505c3fde37e.png)

(I tested on a linux install and the problem don't show up)

Should I open another issue ?

**Comment by engram-design** [comment] 2020-03-03 19:30
@gfra54 All okay here?

**Comment by gfra54** [comment] 2020-03-04 07:27
> 
> 
> @gfra54 All okay here?

I am not 100% sure but I guess that is a pretty niche porblem. I have the same bug happening but it seems to be caused by my migration: I migrated from a linux dev env to a WAMP dev env, and on windows, the icons where messed up. I removed the menu elements and created them again, and it is ok now. I will look again into that and let you know if there is a bug. Cheers ! (And **THANKS** for you work)
