### ISSUE TITLE
Dividers sometimes doesn't show the label

### ISSUE THREAD

**Issue by jmchat** [engram-design/CPNav#97] opened 2021-10-15 19:12 UTC
**Description**
Some pageviews within the control panel show empty divider labels. It's not bound to any errors in the console or other things I can check. It looks like the text is not added when I inspect the divider in chrome.

**Steps to reproduce**
1. Just reload a random page in the control panel for a few times and you might get lucky hitting the empty dividers.

**Additional info**
- Plugin version: 3.0.17
- Craft version: Craft Pro 3.7.16
- Multi-site: Yes

**Additional context**
On Mac and Windows (using Chrome)

![image](https://user-images.githubusercontent.com/46917781/137539584-faba7a3f-ebac-4e8d-a56c-61da29d8a135.png)

**Comment by engram-design** [comment] 2021-10-15 22:11
Duplicate of https://github.com/verbb/cp-nav/issues/82 where it looks like the CSS or JS isn't being loaded. If you can check next time it happens if those classes aren't appearing on the divider elements?

**Comment by engram-design** [comment] 2022-04-12 10:13
Should be fixed in [4.0.0-beta.2](https://github.com/verbb/cp-nav/releases/tag/4.0.0-beta.2) for Craft 4.

**Closed as completed** 2022-05-03 12:06 UTC
