### ISSUE TITLE
Items keep moving and disappearing.

### ISSUE THREAD

**Issue by KatieMFritz** [engram-design/CPNav#60] opened 2019-08-09 16:08 UTC
### Description
I'm only using a single default layout. Items keep showing up in the wrong places in the sidebar. Note Dashboard in this screenshot. Sometimes User Guide isn't showing up at all, especially if Dashboard is disabled. The issue persists and seems to get worse over time. 

![Screen Shot 2019-08-09 at 6 06 10 PM](https://user-images.githubusercontent.com/7085184/62792866-7fb45780-bad0-11e9-8eac-ca65344dbcda.png)

### Steps to reproduce

1. Customize default profile
2. See where items are actually showing up

### Additional info

- Plugin version: 2.0.9
- Craft version: Pro 3.2.9
- Postgres

**Comment by ademers** [comment] 2019-08-20 13:02
I'm having similar issues. Is the plugin supposed to be compatible with Craft 3.2.x? Thanks!

**Comment by KatieMFritz** [comment] 2019-10-28 17:22
Maybe related to #49 ? @ademers have you found any workarounds?

**Comment by ademers** [comment] 2019-10-28 20:15
@KatieMFritz No. I'm leaving it for now. Fortunately it's not a show stopper,

**Comment by engram-design** [comment] 2019-11-27 06:34
@KatieMFritz Hmmm, I think I'll put this in the 3.0 refactor pile. I can't immediately reproduce this, but I'm going to do things from scratch that'll help a lot with performance, and these sorts of issues.

**Comment by fthues** [comment] 2019-12-10 15:09
Here's what I'm seeing:

![cpnav-bug](https://user-images.githubusercontent.com/455982/70541223-ec1a9280-1b66-11ea-8349-8e0b42b2bb9d.gif)

I've got a layout called "Editors" in addition to the default one. There are items missing whenever I activate the "Editors" layout. Things temporarily jump back to normal once I start editing, but when I switch to another layout and back they are gone again.

When I log in as the user group assigned to the new layout the items are missing as well.

Craft Pro 3.3.17
Control Panel Nav 2.0.9
PHP 7.4.0

**Comment by fthues** [comment] 2019-12-10 15:40
Any newly created fields get saved to the database with an empty handle. The payload for the XHR request to `cp-nav/navigation/new` looks like this, note the empty `handle`:

`currLabel=Stations&url=entries%2Fstations&newWindow=&customIcon=&layoutId=2&id=&handle=`

The DOM looks like this, note the `nav-` with missing handle:

![Screen Shot 2019-12-10 at 16 39 11](https://user-images.githubusercontent.com/455982/70544088-cba10700-1b6b-11ea-91e6-01b3ed13bcad.png)

**Comment by fthues** [comment] 2019-12-10 16:23
So for whatever reason Craft's HandleGenerator doesn't like the HUD's hidden input field. I changed it to be a regular text field and it works, see my PR #62 for reference.

**Comment by fthues** [comment] 2019-12-10 16:25
For anyone affected by this issue: Alternatively you can just edit the `cpnav_navigation` table manually and insert the missing handles.

**Comment by engram-design** [comment] 2020-01-20 01:52
This should be fixed in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0) thanks to a major refactor with how this was all done.

**Closed as completed by engram-design** 2020-01-20 01:52 UTC
