### ISSUE TITLE
Ordering gets messed up if you add dividers in 3.4

### ISSUE THREAD

**Issue by adrienne** [engram-design/CPNav#77] opened 2020-04-30 19:18 UTC
### Description

When I add dividers to the menu and then drag items to reorder, everything just gets deeply messed up. Dashboard ends up in a weird and mostly random place, and the dividers don't stay put either.

It doesn't seem to matter whether Project Config is enabled or not; it was enabled to start with, but I disabled it to see if that fixed the issue and it did not.

### Additional info

- Plugin version: Control Panel Nav 3.0.12
- Craft version: Craft Pro 3.4.17.1
--

**Comment by engram-design** [comment] 2020-05-11 13:02
I can't seem to immediately reproduce this. Is the order of items messed up as soon as you change them? The sidebar should re-order immediately when you are editing the menu. Does a page refresh help?

Wondering if you might be able to send through a screenshot of your `cpnav_navigation` database table?

Lastly, it might be worth checking out the latest code where I've simplified how new menu items work. You can install it by running `composer require verbb/cp-nav:dev-craft-3`

**Comment by engram-design** [comment] 2020-11-29 00:03
Closing for now due to age.

**Closed as completed by engram-design** 2020-11-29 00:03 UTC
