### ISSUE TITLE
CP nav randomly adds menu items.

### ISSUE THREAD

**Issue by chillibe** [engram-design/CPNav#49] opened 2018-05-15 08:22 UTC
### Description
CP Nav randomly adds menu items to a layout. I think at some points it still uses the navigation layout from the admin role. I made a screencast to show the problem.
https://chilli.d.pr/XeLEzO/hSK6IFMgl1

### Steps to reproduce

1. Make a new user with an editor role
2. Login in the cp with this new user (Firefox)
3. Login as admin in another browser, Chrome
4. Try to add new menu items in the CP Nav plugin
5. Go to your Firefox browser and refresh
6. Go back to Chrome and refresh
7. The order is wrong and menu items have been added.

### Additional info

- Plugin version: 2.0.6
- Craft version: 3.0.7

**Comment by engram-design** [comment] 2018-07-05 05:20
Sorry for the delay in coming back to you on this, I'm not able the replicate and your screencast has expired (sorry!)

**Comment by juresrpcic** [comment] 2018-07-05 08:00
I'm also getting the same issue, both on local dev (windows, nginx) and on the server (ubuntu 16.04, standard laravel forge setup). Using latest Chrome.

I noticed it affects the "system" menu links now that I'm not touching the custom pages anymore - so Settings, Plugins, Users, any custom Plugin pages. Simple to replicate - I just switch from the Default profile to Editors (same steps as above) and the menu items are suddenly enabled.

If I re-disable them, they stay fine immediately after (if I switch the profiles again) - but when I'll login tomorrow, the same thing will happen again - so I always need to re-disable things if I decide to add something to the Editors menu.

Also had the same issue as described above - but tricky to replicate because it stays fine immediately after trying things... It's definitely connected to switching profiles though.

Happy to do more testing if you have something specific in mind.

**Comment by engram-design** [comment] 2018-07-18 11:07
@juresrpcic Still struggling to reproduce this, with the same instructions as above - over and over! Don't suppose you'd be able to offer a screencast as an example?

**Comment by juresrpcic** [comment] 2018-07-18 12:07
Yes, absolutely, it's always reproducible - but only after there's been a day in between - not sure what triggers this to break. I've recorded a gif:

- the Editor user should not see any admin stuff (Users, Plugins, Settings) and at the start of their recording, it's not showing those items
- when I switch Admin to Editor, you'll see the left menu suddenly shows admin menus (some of them, not sure why not all) and then I refresh the page and it reflects that on the CPNAV list too
- I then have to turn admin menus off again to make them "stick" (until the next time I decide to switch from Admin to Editor the next day for example) - and they do stick temporarily which I show by switching between them at the end

Happy to give more feedback if you let me know what you need...

![cpnav-reset](https://user-images.githubusercontent.com/2803433/42880120-72bd3d62-8a93-11e8-8dbe-fac6f0762745.gif)

**Comment by engram-design** [comment] 2018-07-18 13:44
Ah, this involves multiple layouts, makes sense if I read back through. I believe changes were being made to the correct layout nav items - but it wasn't really showing them in preview fashion. I've made some improvements to this.

Additionally, I've added a notification showing which layout you might be editing. When you edit your 'Editors' layout, you'll get a red banner showing that you are. A small cross allows you to stop previewing the layout and go back to your own (often the default).

If you'd have a chance to test this out via `composer require verbb/cp-nav:dev-craft-3`, I'd be keen to see your feedback.

**Comment by juresrpcic** [comment] 2018-07-27 06:10
Sorry, it took a while until I could set up a proper test env for this, but I have deployed the dev version to a production site now and so far so good - the red "Editing Editors" bar is great! I'll try again in a few days to see if it "sticks" and let you know.

**Comment by juresrpcic** [comment] 2018-07-29 19:35
@engram-design I have tried to replicate the previous error in the past few days but couldn't - so this looks resolved, thanks!

**Comment by engram-design** [comment] 2020-01-20 01:52
This should be fixed in [3.0.0](https://github.com/verbb/cp-nav/releases/tag/3.0.0) thanks to a major refactor with how this was all done.

**Closed as completed by engram-design** 2020-01-20 01:52 UTC
